default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rescue_mission_development

test:
  <<: *default
  database: rescue_mission_test

production:
  <<: *default
  database: rescue_mission_production
  username: rescue_mission
  password: <%= ENV['RESCUE_MISSION_DATABASE_PASSWORD'] %>
