---
title: "Rock, Paper, Scissors"
type: "challenge"
description: "Pit human vs. machine in this riveting, command-line version of the classic game of chance."
depends: "compound-interest-calculator"
ignore:
- "rock-paper-scissors.md"
